### PR TITLE
Chinese translation

### PR DESCRIPTION
**Pull request by ucSec**
Translate from English

### CODE REVIEW

**Comment by ucSec** [comment]
Question: where is "Arch"
截屏2020-04-20 下午3 51 33

**Comment by pavroo** [comment]
it's a short form of Architecture

**Comment by ucSec** [comment]
But I cannot find "Arch" or "Architecture" between LOCAL7 and LOCAL8. Should I add it somewhere? Thanks.

**Comment by pavroo** [comment]
It is not translated in any language, not sure it should be...

**Comment by ucSec** [comment]
However, I think it is not necessary to translate it...

**Pull request merged**
